// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwmuegG8iA377Dz97NKz_9UOvhReVQJtk',
    appId: '1:859037328248:web:1f36a60db34792e3c01e8d',
    messagingSenderId: '859037328248',
    projectId: 'smartlock-fc05a',
    authDomain: 'smartlock-fc05a.firebaseapp.com',
    databaseURL: 'https://smartlock-fc05a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartlock-fc05a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQbh5fK5T5aKpdnV49VfT8TMZd6TkDjWM',
    appId: '1:859037328248:android:2a1524794e2cea30c01e8d',
    messagingSenderId: '859037328248',
    projectId: 'smartlock-fc05a',
    databaseURL: 'https://smartlock-fc05a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartlock-fc05a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByRthTIOdCQ83wzzFUaTXRzxJzmyTk5TI',
    appId: '1:859037328248:ios:3fe501b0b0a9a907c01e8d',
    messagingSenderId: '859037328248',
    projectId: 'smartlock-fc05a',
    databaseURL: 'https://smartlock-fc05a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartlock-fc05a.appspot.com',
    iosClientId: '859037328248-o44nsts94fmbuaocq72k1g8fprvleqf3.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartLockSecurity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByRthTIOdCQ83wzzFUaTXRzxJzmyTk5TI',
    appId: '1:859037328248:ios:3fe501b0b0a9a907c01e8d',
    messagingSenderId: '859037328248',
    projectId: 'smartlock-fc05a',
    databaseURL: 'https://smartlock-fc05a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartlock-fc05a.appspot.com',
    iosClientId: '859037328248-o44nsts94fmbuaocq72k1g8fprvleqf3.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartLockSecurity',
  );
}
